package server;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class SendEmail {

    public static void sendMail() {

        String to = "rmasey@hotmail.com";    // Put recipient’s address
        String from = "from@example.com";    // Put sender’s address
        final String username = "88c43c37f583be";//username generated by Mailtrap
        final String password = "17a7a8c238f5c8";//password generated by Mailtrap

        String host = "smtp.mailtrap.io";          // Paste host address from the SMTP settings tab in your Mailtrap Inbox

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "25");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

        // Get the Session object.
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });
        try {
            Message message = new MimeMessage(session);         // Create a default MimeMessage object.
            message.setFrom(new InternetAddress(from));      // Set From: header field
            message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(to));   // Set To: header field
            message.setSubject("My first message with JavaMail");  // Set Subject: header field
            message.setText("Hi there, this is my first message sent with JavaMail");        // Put the content of your message
            Transport.send(message);          // Send message
            System.out.println("Sent message successfully....");
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
}